# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_VeresiyeDefterim(object):
    def setupUi(self, VeresiyeDefterim):
        VeresiyeDefterim.setObjectName("VeresiyeDefterim")
        VeresiyeDefterim.resize(756, 640)
        self.frame = QtWidgets.QFrame(VeresiyeDefterim)
        self.frame.setGeometry(QtCore.QRect(10, 10, 731, 611))
        self.frame.setMinimumSize(QtCore.QSize(0, 611))
        self.frame.setMaximumSize(QtCore.QSize(731, 611))
        self.frame.setStyleSheet("QFrame{\n"
"   background-color:rgb(56,58,89);\n"
"   color:rgb(253, 0, 0);\n"
"   border-radius:10px;\n"
"\n"
"\n"
"}")
        self.frame.setObjectName("frame")
        self.Kayit_buton = QtWidgets.QPushButton(self.frame)
        self.Kayit_buton.setGeometry(QtCore.QRect(10, 160, 113, 32))
        self.Kayit_buton.setObjectName("Kayit_buton")
        self.Sil_buton = QtWidgets.QPushButton(self.frame)
        self.Sil_buton.setGeometry(QtCore.QRect(10, 200, 113, 32))
        self.Sil_buton.setObjectName("Sil_buton")
        self.Musteri_bul_buton = QtWidgets.QPushButton(self.frame)
        self.Musteri_bul_buton.setGeometry(QtCore.QRect(10, 240, 113, 32))
        self.Musteri_bul_buton.setObjectName("Musteri_bul_buton")
        self.Musteri_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.Musteri_lineEdit.setGeometry(QtCore.QRect(10, 280, 113, 21))
        self.Musteri_lineEdit.setStyleSheet("  border-radius:10px;")
        self.Musteri_lineEdit.setObjectName("Musteri_lineEdit")
        self.Musteri_label = QtWidgets.QLabel(self.frame)
        self.Musteri_label.setGeometry(QtCore.QRect(30, 50, 101, 21))
        self.Musteri_label.setObjectName("Musteri_label")
        self.isim_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.isim_lineEdit.setGeometry(QtCore.QRect(20, 80, 113, 21))
        self.isim_lineEdit.setStyleSheet("  border-radius:10px;")
        self.isim_lineEdit.setObjectName("isim_lineEdit")
        self.AldigiFiyat_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.AldigiFiyat_lineEdit.setGeometry(QtCore.QRect(170, 80, 113, 21))
        self.AldigiFiyat_lineEdit.setStyleSheet("  border-radius:10px;")
        self.AldigiFiyat_lineEdit.setObjectName("AldigiFiyat_lineEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(340, 50, 81, 16))
        self.label.setStyleSheet("QFrame{qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 48, 0, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(320, 80, 113, 21))
        self.lineEdit.setStyleSheet("  border-radius:10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(460, 80, 113, 21))
        self.lineEdit_2.setStyleSheet("  border-radius:10px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(180, 50, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(480, 50, 71, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(590, 80, 113, 21))
        self.lineEdit_4.setStyleSheet("  border-radius:10px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(610, 50, 81, 16))
        self.label_7.setObjectName("label_7")
        self.tableWidget = QtWidgets.QTableWidget(VeresiyeDefterim)
        self.tableWidget.setGeometry(QtCore.QRect(210, 150, 491, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.Kayit_buton.clicked.connect(self.kayit_clicked)
        self.Sil_buton.clicked.connect(self.Silme_clicked)
        self.Musteri_bul_buton.clicked.connect(self.Baglanti_clicked)

        self.retranslateUi(VeresiyeDefterim)
        QtCore.QMetaObject.connectSlotsByName(VeresiyeDefterim)

    def retranslateUi(self, VeresiyeDefterim):
        _translate = QtCore.QCoreApplication.translate
        VeresiyeDefterim.setWindowTitle(_translate("VeresiyeDefterim", "Form"))
        VeresiyeDefterim.setToolTip(_translate("VeresiyeDefterim", "<html><head/><body><p><br/></p></body></html>"))
        self.Kayit_buton.setText(_translate("VeresiyeDefterim", "Kayıt et"))
        self.Sil_buton.setText(_translate("VeresiyeDefterim", "sil"))
        self.Musteri_bul_buton.setText(_translate("VeresiyeDefterim", "Müşteriyi bul:"))
        self.Musteri_label.setText(_translate("VeresiyeDefterim", "<html><head/><body><p><span style=\" font-weight:600;\">Müşteri İsmi:</span></p></body></html>"))
        self.label.setText(_translate("VeresiyeDefterim", "<html><head/><body><p><span style=\" font-weight:600;\">Aldığı Ürün:</span></p></body></html>"))
        self.label_4.setText(_translate("VeresiyeDefterim", "<html><head/><body><p><span style=\" font-weight:600;\">Aldığı Fiyat:</span></p></body></html>"))
        self.label_6.setText(_translate("VeresiyeDefterim", "<html><head/><body><p><span style=\" font-weight:600;\">Açıklama:</span></p></body></html>"))
        self.label_7.setText(_translate("VeresiyeDefterim", "<html><head/><body><p><span style=\" font-weight:600;\">İşlem Tarihi:</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("VeresiyeDefterim", "Ad"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("VeresiyeDefterim", "Aldığı ürün"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("VeresiyeDefterim", "Aldığı fiyat"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("VeresiyeDefterim", "acıklama"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("VeresiyeDefterim", "tarih"))

    def kayit_clicked(self, VeresiyeDefterim):
        baglantı = sqlite3.connect("veri2.db")

        self.cursor = baglantı.cursor()
        ad = self.isim_lineEdit.text()
        aldigi_fiyat = self.AldigiFiyat_lineEdit.text()
        aldigi_urun = self.lineEdit.text()
        aciklama = self.lineEdit_2.text()
        tarih = self.lineEdit_4.text()

        self.cursor.execute(
            "CREATE TABLE IF NOT EXISTS veri2 (Ad TEXT, Aldigi_Fiyat INTEGER,Aldigi_urun TEXT,Aciklama TEXT,Tarih TEXT)")
        self.cursor.execute("INSERT INTO veri2 VALUES (?,?,?,?,?)", (ad, aldigi_fiyat, aldigi_urun, aciklama, tarih))
        baglantı.commit()

    def Silme_clicked(self, VeresiyeDefterim):
        baglantı = sqlite3.connect("veri2.db")
        self.cursor = baglantı.cursor()
        silinecek = self.isim_lineEdit.text()
        self.cursor.execute("DELETE FROM  veri2 WHERE Ad ='%s'" % (silinecek))

        baglantı.commit()

    def Baglanti_clicked(self, VeresiyeDefterim):
        conn = sqlite3.connect("veri2.db")
        self.cursor = conn.cursor()
        musteri = self.Musteri_lineEdit.text()
        self.cursor.execute("SELECT * FROM veri2 ")
        data = self.cursor.fetchall()
        new_data = []
        for i in data:
            for j in i:
                if musteri in str(j):
                    new_data.append(i)
                    break
        self.tableWidget.insertRow(0)
        for row, form in enumerate(new_data):
            for column, item in enumerate(form):
                self.tableWidget.setItem(row, column, QtWidgets.QTableWidgetItem(str(item)))
                column += 1
            row_pozisyon = self.tableWidget.rowCount()
            self.tableWidget.insertRow(row_pozisyon)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VeresiyeDefterim = QtWidgets.QWidget()
    ui = Ui_VeresiyeDefterim()
    ui.setupUi(VeresiyeDefterim)
    VeresiyeDefterim.show()
    sys.exit(app.exec_())
